//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Worker
    {
        public int WorkerId { get; set; }
        public int UserId { get; set; }
        public int HotelFloor { get; set; }
        public int GenderId { get; set; }
        public string Citizenship { get; set; }
        public int EngagementId { get; set; }
        public Nullable<decimal> Salary { get; set; }
    
        public virtual Engagement Engagement { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual UserHotel UserHotel { get; set; }
    }
}
